var MODELS = {
	'model_mm1': {
		model: '{"until":14400,"seed":1234,"version":"1.0","objects":[{"x":102,"y":136,"type":"source","name":"source_1","out":"queue_1","model":{"lambda":0.25}},{"x":252,"y":93,"type":"queue","name":"queue_1","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}}]}'
	},
	
	'model_mm1feedback': {
		model: '{"until":14400,"seed":1234,"version":"1.0","objects":[{"x":399,"y":171,"type":"sink","name":"sink_1","model":null},{"x":257,"y":186,"type":"splitter","name":"splitter_1","out":["queue_1","sink_1"],"model":{"prob":"0.1"}},{"x":102,"y":136,"type":"source","name":"source_1","out":"queue_1","model":{"lambda":0.25}},{"x":210,"y":83,"type":"queue","name":"queue_1","out":"splitter_1","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}}]}'
	},
	
	'model_backforth': {
		model: '{"until":14400,"seed":1234,"version":"1.0","objects":[{"x":505,"y":208,"type":"sink","name":"sink_2","model":null},{"x":492,"y":79,"type":"sink","name":"sink_1","model":null},{"x":241,"y":187,"type":"queue","name":"queue_2","out":"splitter_2","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}},{"x":396,"y":186,"type":"splitter","name":"splitter_2","out":["queue_1","sink_2"],"model":{"prob":"0.1"}},{"x":377,"y":87,"type":"splitter","name":"splitter_1","out":["sink_1","queue_2"],"model":{"prob":"0.9"}},{"x":228,"y":87,"type":"queue","name":"queue_1","out":"splitter_1","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}},{"x":91,"y":84,"type":"source","name":"source_1","out":"queue_1","model":{"lambda":0.25}}]}'
	},
	
	'model_waterfall': {
		model: '{"until":14400,"seed":1234,"version":"1.0","objects":[{"x":82,"y":29,"type":"source","name":"source_1","out":"queue_1","model":{"lambda":0.25}},{"x":558,"y":341,"type":"sink","name":"sink_1","model":null},{"x":440,"y":281,"type":"queue","name":"queue_4","out":"sink_1","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}},{"x":342,"y":211,"type":"queue","name":"queue_3","out":"queue_4","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}},{"x":241,"y":144,"type":"queue","name":"queue_2","out":"queue_3","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}},{"x":140,"y":76,"type":"queue","name":"queue_1","out":"queue_2","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}}]}'
	},
	
	'model_freeway': {
		model: '{"until":28800,"seed":1234,"version":"1.0","objects":[{"x":380,"y":2,"type":"source","name":"source_4","out":"queue_4","model":{"lambda":0.25}},{"x":255,"y":80,"type":"source","name":"source_3","out":"queue_3","model":{"lambda":0.25}},{"x":115,"y":181,"type":"source","name":"source_2","out":"queue_2","model":{"lambda":0.25}},{"x":8,"y":229,"type":"source","name":"source_1","out":"queue_1","model":{"lambda":0.25}},{"x":561,"y":105,"type":"sink","name":"sink_4","model":null},{"x":543,"y":209,"type":"sink","name":"sink_3","model":null},{"x":412,"y":285,"type":"sink","name":"sink_2","model":null},{"x":236,"y":342,"type":"sink","name":"sink_1","model":null},{"x":170,"y":278,"type":"splitter","name":"splitter_3","out":["queue_2","sink_1"],"model":{"prob":0.5}},{"x":342,"y":206,"type":"splitter","name":"splitter_2","out":["queue_3","sink_2"],"model":{"prob":0.5}},{"x":468,"y":129,"type":"splitter","name":"splitter_1","out":["queue_4","sink_3"],"model":{"prob":0.5}},{"x":479,"y":25,"type":"queue","name":"queue_4","out":"sink_4","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}},{"x":327,"y":132,"type":"queue","name":"queue_3","out":"splitter_1","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}},{"x":194,"y":207,"type":"queue","name":"queue_2","out":"splitter_2","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}},{"x":31,"y":281,"type":"queue","name":"queue_1","out":"splitter_3","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}}]}'
	},
	
	'model_staytillend': {
		model: '{"until":14400,"seed":1234,"version":"1.0","objects":[{"x":471,"y":211,"type":"splitter","name":"splitter_3","out":["sink_3","queue_4"],"model":{"prob":0.5}},{"x":369,"y":141,"type":"splitter","name":"splitter_2","out":["sink_2","queue_3"],"model":{"prob":0.5}},{"x":254,"y":73,"type":"splitter","name":"splitter_1","out":["sink_1","queue_2"],"model":{"prob":0.5}},{"x":561,"y":242,"type":"sink","name":"sink_4","model":null},{"x":520,"y":159,"type":"sink","name":"sink_3","model":null},{"x":438,"y":97,"type":"sink","name":"sink_2","model":null},{"x":82,"y":29,"type":"source","name":"source_1","out":"queue_1","model":{"lambda":0.25}},{"x":314,"y":39,"type":"sink","name":"sink_1","model":null},{"x":440,"y":281,"type":"queue","name":"queue_4","out":"sink_4","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}},{"x":342,"y":211,"type":"queue","name":"queue_3","out":"splitter_3","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}},{"x":241,"y":144,"type":"queue","name":"queue_2","out":"splitter_2","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}},{"x":140,"y":76,"type":"queue","name":"queue_1","out":"splitter_1","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}}]}'
	},
	
	'model_winner': {
		model: '{"until":28800,"seed":1234,"version":"1.0","objects":[{"x":395,"y":9,"type":"sink","name":"sink_7","model":null},{"x":542,"y":126,"type":"sink","name":"sink_6","model":null},{"x":272,"y":128,"type":"sink","name":"sink_5","model":null},{"x":566,"y":241,"type":"sink","name":"sink_4","model":null},{"x":457,"y":250,"type":"sink","name":"sink_3","model":null},{"x":316,"y":247,"type":"sink","name":"sink_2","model":null},{"x":170,"y":234,"type":"sink","name":"sink_1","model":null},{"x":260,"y":265,"type":"splitter","name":"splitter_6","out":["queue_5","sink_2"],"model":{"prob":0.5}},{"x":405,"y":251,"type":"splitter","name":"splitter_5","out":["queue_6","sink_3"],"model":{"prob":0.5}},{"x":509,"y":233,"type":"splitter","name":"splitter_4","out":["queue_6","sink_4"],"model":{"prob":0.5}},{"x":421,"y":358,"type":"source","name":"source_4","out":"queue_4","model":{"lambda":0.25}},{"x":298,"y":358,"type":"source","name":"source_3","out":"queue_3","model":{"lambda":0.25}},{"x":133,"y":352,"type":"source","name":"source_2","out":"queue_2","model":{"lambda":0.25}},{"x":17,"y":347,"type":"source","name":"source_1","out":"queue_1","model":{"lambda":0.25}},{"x":117,"y":253,"type":"splitter","name":"splitter_3","out":["queue_5","sink_1"],"model":{"prob":0.5}},{"x":468,"y":119,"type":"splitter","name":"splitter_2","out":["queue_7","sink_6"],"model":{"prob":0.5}},{"x":207,"y":123,"type":"splitter","name":"splitter_1","out":["queue_7","sink_5"],"model":{"prob":0.5}},{"x":278,"y":58,"type":"queue","name":"queue_7","out":"sink_7","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}},{"x":360,"y":154,"type":"queue","name":"queue_6","out":"splitter_2","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}},{"x":97,"y":146,"type":"queue","name":"queue_5","out":"splitter_1","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}},{"x":466,"y":291,"type":"queue","name":"queue_4","out":"splitter_4","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}},{"x":333,"y":291,"type":"queue","name":"queue_3","out":"splitter_5","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}},{"x":161,"y":292,"type":"queue","name":"queue_2","out":"splitter_6","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}},{"x":21,"y":291,"type":"queue","name":"queue_1","out":"splitter_3","model":{"nservers":1,"mu":1,"infinite":true,"maxqlen":0}}]}'
	}
};